version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: thesis_manager
      POSTGRES_PASSWORD: thesis_manager
      POSTGRES_DB: thesis_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thesis_manager -d thesis_manager"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD : admin
    command: >
      start-dev
      --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    ports:
      - 8080:8080
    restart: unless-stopped

volumes:
  postgres_data:
