version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD : admin
    command: >
      start-dev
      --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    ports:
      - 8080:8080
    restart: unless-stopped
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ThesisManagement
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_PORT: 5432
    shm_size: 256mb
    ports:
      - 5433:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ThesisManagement"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

