# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user_id import UserId  # noqa: F401,E501
from swagger_server import util


class Comment(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, author: UserId=None, message: str=None):  # noqa: E501
        """Comment - a model defined in Swagger

        :param author: The author of this Comment.  # noqa: E501
        :type author: UserId
        :param message: The message of this Comment.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'author': UserId,
            'message': str
        }

        self.attribute_map = {
            'author': 'author',
            'message': 'message'
        }
        self._author = author
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'Comment':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Comment of this Comment.  # noqa: E501
        :rtype: Comment
        """
        return util.deserialize_model(dikt, cls)

    @property
    def author(self) -> UserId:
        """Gets the author of this Comment.


        :return: The author of this Comment.
        :rtype: UserId
        """
        return self._author

    @author.setter
    def author(self, author: UserId):
        """Sets the author of this Comment.


        :param author: The author of this Comment.
        :type author: UserId
        """

        self._author = author

    @property
    def message(self) -> str:
        """Gets the message of this Comment.


        :return: The message of this Comment.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this Comment.


        :param message: The message of this Comment.
        :type message: str
        """

        self._message = message
