# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2041(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ok: object=None):  # noqa: E501
        """InlineResponse2041 - a model defined in Swagger

        :param ok: The ok of this InlineResponse2041.  # noqa: E501
        :type ok: object
        """
        self.swagger_types = {
            'ok': object
        }

        self.attribute_map = {
            'ok': 'ok'
        }
        self._ok = ok

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2041':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_204_1 of this InlineResponse2041.  # noqa: E501
        :rtype: InlineResponse2041
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ok(self) -> object:
        """Gets the ok of this InlineResponse2041.


        :return: The ok of this InlineResponse2041.
        :rtype: object
        """
        return self._ok

    @ok.setter
    def ok(self, ok: object):
        """Sets the ok of this InlineResponse2041.


        :param ok: The ok of this InlineResponse2041.
        :type ok: object
        """

        self._ok = ok
