# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.comment import Comment  # noqa: F401,E501
from swagger_server import util


class InlineResponse2011(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ok: Comment=None):  # noqa: E501
        """InlineResponse2011 - a model defined in Swagger

        :param ok: The ok of this InlineResponse2011.  # noqa: E501
        :type ok: Comment
        """
        self.swagger_types = {
            'ok': Comment
        }

        self.attribute_map = {
            'ok': 'ok'
        }
        self._ok = ok

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2011':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201_1 of this InlineResponse2011.  # noqa: E501
        :rtype: InlineResponse2011
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ok(self) -> Comment:
        """Gets the ok of this InlineResponse2011.


        :return: The ok of this InlineResponse2011.
        :rtype: Comment
        """
        return self._ok

    @ok.setter
    def ok(self, ok: Comment):
        """Sets the ok of this InlineResponse2011.


        :param ok: The ok of this InlineResponse2011.
        :type ok: Comment
        """

        self._ok = ok
