# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user import User  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ok: List[User]=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param ok: The ok of this InlineResponse200.  # noqa: E501
        :type ok: List[User]
        """
        self.swagger_types = {
            'ok': List[User]
        }

        self.attribute_map = {
            'ok': 'ok'
        }
        self._ok = ok

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ok(self) -> List[User]:
        """Gets the ok of this InlineResponse200.


        :return: The ok of this InlineResponse200.
        :rtype: List[User]
        """
        return self._ok

    @ok.setter
    def ok(self, ok: List[User]):
        """Sets the ok of this InlineResponse200.


        :param ok: The ok of this InlineResponse200.
        :type ok: List[User]
        """

        self._ok = ok
