# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user import User  # noqa: F401,E501
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ok: User=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param ok: The ok of this InlineResponse2001.  # noqa: E501
        :type ok: User
        """
        self.swagger_types = {
            'ok': User
        }

        self.attribute_map = {
            'ok': 'ok'
        }
        self._ok = ok

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ok(self) -> User:
        """Gets the ok of this InlineResponse2001.


        :return: The ok of this InlineResponse2001.
        :rtype: User
        """
        return self._ok

    @ok.setter
    def ok(self, ok: User):
        """Sets the ok of this InlineResponse2001.


        :param ok: The ok of this InlineResponse2001.
        :type ok: User
        """

        self._ok = ok
