# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.comment import Comment  # noqa: F401,E501
from swagger_server import util


class InlineResponse2003(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ok: List[Comment]=None):  # noqa: E501
        """InlineResponse2003 - a model defined in Swagger

        :param ok: The ok of this InlineResponse2003.  # noqa: E501
        :type ok: List[Comment]
        """
        self.swagger_types = {
            'ok': List[Comment]
        }

        self.attribute_map = {
            'ok': 'ok'
        }
        self._ok = ok

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2003':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_3 of this InlineResponse2003.  # noqa: E501
        :rtype: InlineResponse2003
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ok(self) -> List[Comment]:
        """Gets the ok of this InlineResponse2003.


        :return: The ok of this InlineResponse2003.
        :rtype: List[Comment]
        """
        return self._ok

    @ok.setter
    def ok(self, ok: List[Comment]):
        """Sets the ok of this InlineResponse2003.


        :param ok: The ok of this InlineResponse2003.
        :type ok: List[Comment]
        """

        self._ok = ok
