# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.registration_token import RegistrationToken  # noqa: F401,E501
from swagger_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ok: RegistrationToken=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger

        :param ok: The ok of this InlineResponse2002.  # noqa: E501
        :type ok: RegistrationToken
        """
        self.swagger_types = {
            'ok': RegistrationToken
        }

        self.attribute_map = {
            'ok': 'ok'
        }
        self._ok = ok

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ok(self) -> RegistrationToken:
        """Gets the ok of this InlineResponse2002.


        :return: The ok of this InlineResponse2002.
        :rtype: RegistrationToken
        """
        return self._ok

    @ok.setter
    def ok(self, ok: RegistrationToken):
        """Sets the ok of this InlineResponse2002.


        :param ok: The ok of this InlineResponse2002.
        :type ok: RegistrationToken
        """

        self._ok = ok
