# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user_id import UserId  # noqa: F401,E501
from swagger_server import util


class InlineResponse204(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ok: List[UserId]=None):  # noqa: E501
        """InlineResponse204 - a model defined in Swagger

        :param ok: The ok of this InlineResponse204.  # noqa: E501
        :type ok: List[UserId]
        """
        self.swagger_types = {
            'ok': List[UserId]
        }

        self.attribute_map = {
            'ok': 'ok'
        }
        self._ok = ok

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse204':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_204 of this InlineResponse204.  # noqa: E501
        :rtype: InlineResponse204
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ok(self) -> List[UserId]:
        """Gets the ok of this InlineResponse204.


        :return: The ok of this InlineResponse204.
        :rtype: List[UserId]
        """
        return self._ok

    @ok.setter
    def ok(self, ok: List[UserId]):
        """Sets the ok of this InlineResponse204.


        :param ok: The ok of this InlineResponse204.
        :type ok: List[UserId]
        """

        self._ok = ok
