# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ThesisPartnerCompanyAddress(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, street: str=None, zip_code: int=None, city: str=None):  # noqa: E501
        """ThesisPartnerCompanyAddress - a model defined in Swagger

        :param street: The street of this ThesisPartnerCompanyAddress.  # noqa: E501
        :type street: str
        :param zip_code: The zip_code of this ThesisPartnerCompanyAddress.  # noqa: E501
        :type zip_code: int
        :param city: The city of this ThesisPartnerCompanyAddress.  # noqa: E501
        :type city: str
        """
        self.swagger_types = {
            'street': str,
            'zip_code': int,
            'city': str
        }

        self.attribute_map = {
            'street': 'street',
            'zip_code': 'zipCode',
            'city': 'city'
        }
        self._street = street
        self._zip_code = zip_code
        self._city = city

    @classmethod
    def from_dict(cls, dikt) -> 'ThesisPartnerCompanyAddress':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Thesis_partnerCompany_address of this ThesisPartnerCompanyAddress.  # noqa: E501
        :rtype: ThesisPartnerCompanyAddress
        """
        return util.deserialize_model(dikt, cls)

    @property
    def street(self) -> str:
        """Gets the street of this ThesisPartnerCompanyAddress.


        :return: The street of this ThesisPartnerCompanyAddress.
        :rtype: str
        """
        return self._street

    @street.setter
    def street(self, street: str):
        """Sets the street of this ThesisPartnerCompanyAddress.


        :param street: The street of this ThesisPartnerCompanyAddress.
        :type street: str
        """

        self._street = street

    @property
    def zip_code(self) -> int:
        """Gets the zip_code of this ThesisPartnerCompanyAddress.


        :return: The zip_code of this ThesisPartnerCompanyAddress.
        :rtype: int
        """
        return self._zip_code

    @zip_code.setter
    def zip_code(self, zip_code: int):
        """Sets the zip_code of this ThesisPartnerCompanyAddress.


        :param zip_code: The zip_code of this ThesisPartnerCompanyAddress.
        :type zip_code: int
        """

        self._zip_code = zip_code

    @property
    def city(self) -> str:
        """Gets the city of this ThesisPartnerCompanyAddress.


        :return: The city of this ThesisPartnerCompanyAddress.
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city: str):
        """Sets the city of this ThesisPartnerCompanyAddress.


        :param city: The city of this ThesisPartnerCompanyAddress.
        :type city: str
        """

        self._city = city
