# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.thesis_id import ThesisId  # noqa: F401,E501
from swagger_server import util


class ThesisSummary(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: ThesisId=None, title: str=None, student_first_name: str=None, student_last_name: str=None):  # noqa: E501
        """ThesisSummary - a model defined in Swagger

        :param id: The id of this ThesisSummary.  # noqa: E501
        :type id: ThesisId
        :param title: The title of this ThesisSummary.  # noqa: E501
        :type title: str
        :param student_first_name: The student_first_name of this ThesisSummary.  # noqa: E501
        :type student_first_name: str
        :param student_last_name: The student_last_name of this ThesisSummary.  # noqa: E501
        :type student_last_name: str
        """
        self.swagger_types = {
            'id': ThesisId,
            'title': str,
            'student_first_name': str,
            'student_last_name': str
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'student_first_name': 'studentFirstName',
            'student_last_name': 'studentLastName'
        }
        self._id = id
        self._title = title
        self._student_first_name = student_first_name
        self._student_last_name = student_last_name

    @classmethod
    def from_dict(cls, dikt) -> 'ThesisSummary':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ThesisSummary of this ThesisSummary.  # noqa: E501
        :rtype: ThesisSummary
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> ThesisId:
        """Gets the id of this ThesisSummary.


        :return: The id of this ThesisSummary.
        :rtype: ThesisId
        """
        return self._id

    @id.setter
    def id(self, id: ThesisId):
        """Sets the id of this ThesisSummary.


        :param id: The id of this ThesisSummary.
        :type id: ThesisId
        """

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this ThesisSummary.


        :return: The title of this ThesisSummary.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this ThesisSummary.


        :param title: The title of this ThesisSummary.
        :type title: str
        """

        self._title = title

    @property
    def student_first_name(self) -> str:
        """Gets the student_first_name of this ThesisSummary.


        :return: The student_first_name of this ThesisSummary.
        :rtype: str
        """
        return self._student_first_name

    @student_first_name.setter
    def student_first_name(self, student_first_name: str):
        """Sets the student_first_name of this ThesisSummary.


        :param student_first_name: The student_first_name of this ThesisSummary.
        :type student_first_name: str
        """

        self._student_first_name = student_first_name

    @property
    def student_last_name(self) -> str:
        """Gets the student_last_name of this ThesisSummary.


        :return: The student_last_name of this ThesisSummary.
        :rtype: str
        """
        return self._student_last_name

    @student_last_name.setter
    def student_last_name(self, student_last_name: str):
        """Sets the student_last_name of this ThesisSummary.


        :param student_last_name: The student_last_name of this ThesisSummary.
        :type student_last_name: str
        """

        self._student_last_name = student_last_name
