# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.thesis_partner_company_address import ThesisPartnerCompanyAddress  # noqa: F401,E501
from swagger_server import util


class ThesisPartnerCompany(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, address: ThesisPartnerCompanyAddress=None):  # noqa: E501
        """ThesisPartnerCompany - a model defined in Swagger

        :param name: The name of this ThesisPartnerCompany.  # noqa: E501
        :type name: str
        :param address: The address of this ThesisPartnerCompany.  # noqa: E501
        :type address: ThesisPartnerCompanyAddress
        """
        self.swagger_types = {
            'name': str,
            'address': ThesisPartnerCompanyAddress
        }

        self.attribute_map = {
            'name': 'name',
            'address': 'address'
        }
        self._name = name
        self._address = address

    @classmethod
    def from_dict(cls, dikt) -> 'ThesisPartnerCompany':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Thesis_partnerCompany of this ThesisPartnerCompany.  # noqa: E501
        :rtype: ThesisPartnerCompany
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this ThesisPartnerCompany.


        :return: The name of this ThesisPartnerCompany.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ThesisPartnerCompany.


        :param name: The name of this ThesisPartnerCompany.
        :type name: str
        """

        self._name = name

    @property
    def address(self) -> ThesisPartnerCompanyAddress:
        """Gets the address of this ThesisPartnerCompany.


        :return: The address of this ThesisPartnerCompany.
        :rtype: ThesisPartnerCompanyAddress
        """
        return self._address

    @address.setter
    def address(self, address: ThesisPartnerCompanyAddress):
        """Sets the address of this ThesisPartnerCompany.


        :param address: The address of this ThesisPartnerCompany.
        :type address: ThesisPartnerCompanyAddress
        """

        self._address = address
