# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AcceptnotifyBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, mail_addresses: str=None, thesis_id: int=None):  # noqa: E501
        """AcceptnotifyBody - a model defined in Swagger

        :param name: The name of this AcceptnotifyBody.  # noqa: E501
        :type name: str
        :param mail_addresses: The mail_addresses of this AcceptnotifyBody.  # noqa: E501
        :type mail_addresses: str
        :param thesis_id: The thesis_id of this AcceptnotifyBody.  # noqa: E501
        :type thesis_id: int
        """
        self.swagger_types = {
            'name': str,
            'mail_addresses': str,
            'thesis_id': int
        }

        self.attribute_map = {
            'name': 'name',
            'mail_addresses': 'mailAddresses',
            'thesis_id': 'ThesisId'
        }
        self._name = name
        self._mail_addresses = mail_addresses
        self._thesis_id = thesis_id

    @classmethod
    def from_dict(cls, dikt) -> 'AcceptnotifyBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The acceptnotify_body of this AcceptnotifyBody.  # noqa: E501
        :rtype: AcceptnotifyBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this AcceptnotifyBody.

        Name of the student  # noqa: E501

        :return: The name of this AcceptnotifyBody.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this AcceptnotifyBody.

        Name of the student  # noqa: E501

        :param name: The name of this AcceptnotifyBody.
        :type name: str
        """

        self._name = name

    @property
    def mail_addresses(self) -> str:
        """Gets the mail_addresses of this AcceptnotifyBody.

        Email addresses of recipient  # noqa: E501

        :return: The mail_addresses of this AcceptnotifyBody.
        :rtype: str
        """
        return self._mail_addresses

    @mail_addresses.setter
    def mail_addresses(self, mail_addresses: str):
        """Sets the mail_addresses of this AcceptnotifyBody.

        Email addresses of recipient  # noqa: E501

        :param mail_addresses: The mail_addresses of this AcceptnotifyBody.
        :type mail_addresses: str
        """

        self._mail_addresses = mail_addresses

    @property
    def thesis_id(self) -> int:
        """Gets the thesis_id of this AcceptnotifyBody.


        :return: The thesis_id of this AcceptnotifyBody.
        :rtype: int
        """
        return self._thesis_id

    @thesis_id.setter
    def thesis_id(self, thesis_id: int):
        """Sets the thesis_id of this AcceptnotifyBody.


        :param thesis_id: The thesis_id of this AcceptnotifyBody.
        :type thesis_id: int
        """

        self._thesis_id = thesis_id
