# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DeadlinereachedBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: List[str]=None, mail_addresses: List[str]=None):  # noqa: E501
        """DeadlinereachedBody - a model defined in Swagger

        :param name: The name of this DeadlinereachedBody.  # noqa: E501
        :type name: List[str]
        :param mail_addresses: The mail_addresses of this DeadlinereachedBody.  # noqa: E501
        :type mail_addresses: List[str]
        """
        self.swagger_types = {
            'name': List[str],
            'mail_addresses': List[str]
        }

        self.attribute_map = {
            'name': 'name',
            'mail_addresses': 'mailAddresses'
        }
        self._name = name
        self._mail_addresses = mail_addresses

    @classmethod
    def from_dict(cls, dikt) -> 'DeadlinereachedBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The deadlinereached_body of this DeadlinereachedBody.  # noqa: E501
        :rtype: DeadlinereachedBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> List[str]:
        """Gets the name of this DeadlinereachedBody.

        List of recipient names  # noqa: E501

        :return: The name of this DeadlinereachedBody.
        :rtype: List[str]
        """
        return self._name

    @name.setter
    def name(self, name: List[str]):
        """Sets the name of this DeadlinereachedBody.

        List of recipient names  # noqa: E501

        :param name: The name of this DeadlinereachedBody.
        :type name: List[str]
        """

        self._name = name

    @property
    def mail_addresses(self) -> List[str]:
        """Gets the mail_addresses of this DeadlinereachedBody.

        List of email addresses  # noqa: E501

        :return: The mail_addresses of this DeadlinereachedBody.
        :rtype: List[str]
        """
        return self._mail_addresses

    @mail_addresses.setter
    def mail_addresses(self, mail_addresses: List[str]):
        """Sets the mail_addresses of this DeadlinereachedBody.

        List of email addresses  # noqa: E501

        :param mail_addresses: The mail_addresses of this DeadlinereachedBody.
        :type mail_addresses: List[str]
        """

        self._mail_addresses = mail_addresses
